const whatsappUrl="https://wa.me/";
const navLinks=[
["Home","index.html","home"],["Cricket","cricket-exchange.html","cricket"],["Football","football-exchange.html","football"],["Casino","casino-games.html","casino"],["Live Casino","live-casino.html","live"],["Aviator","aviator.html","aviator"],["Promotions","promotions.html","promotions"],["VIP","vip-club.html","vip"],["Blog","blog.html","blog"],["FAQ","faq.html","faq"]
];
const commonFaq=[
["Is GATHR a gaming operator?","GATHR is presented as an informational sports exchange and casino guide website. Always review local laws, platform terms and responsible gaming rules before using any third-party service."],
["Who should use this website?","The content is intended for adults aged 18+ who want structured information about sports exchange, casino formats, VIP programs and safer play habits."],
["Does GATHR guarantee winnings?","No. Gaming outcomes are uncertain. GATHR avoids misleading claims and encourages budget limits, time limits and informed choices."]
];
const features=["Fast Withdrawals","Secure Platform","24x7 Support","Mobile Friendly","Premium Experience","VIP Rewards"];
const sports=["Cricket Exchange","Football Exchange","Tennis Exchange","Live Sports"];
const casino=["Live Casino","Slots","Blackjack","Roulette","Baccarat","Teen Patti","Dragon Tiger","Andar Bahar"];
const blogPosts=[
["Online Cricket ID Guide","Online Cricket ID","A clear guide to cricket ID basics, verification questions, safety checks and responsible access for cricket fans.","blog-online-cricket-id.html","online-cricket-id"],
["Cricket Exchange Strategy Basics","Cricket Exchange","Learn how match markets, live odds and T20 momentum are commonly discussed without treating sport as a certainty.","blog-cricket-exchange.html","cricket-exchange-guide"],
["Cricket Betting Guide for Beginners","Cricket Betting Guide","A beginner-friendly article about terminology, bankroll discipline, legal checks and safer decision-making.","blog-cricket-betting-guide.html","cricket-betting-guide"],
["Cricket ID Provider Checklist","Cricket ID Provider","What to compare before choosing any provider: reputation, support, privacy, terms and responsible gaming tools.","blog-cricket-id-provider.html","cricket-id-provider"],
["Best Cricket ID Comparison","Best Cricket ID","How to evaluate the best cricket ID options by support, safety, access and transparent terms.","blog-best-cricket-id.html","best-cricket-id"],
["Online Betting Guide","Online Betting Guide","A responsible guide to online betting concepts, account safety, limits and legal awareness.","blog-online-betting-guide.html","online-betting-guide"],
["IPL Guide and T20 Match Flow","IPL Guide","Understand IPL and T20 formats, team news, match tempo and why discipline matters in short-format cricket.","blog-ipl-guide.html","ipl-guide"],
["T20 Betting Guide","T20 Betting Guide","T20 cricket moves fast. Learn how to read context while keeping strict limits and realistic expectations.","blog-t20-betting-guide.html","t20-betting-guide"],
["Sports Exchange Guide","Sports Exchange Guide","A practical overview of exchange-style markets across cricket, football, tennis and live sports.","blog-sports-exchange-guide.html","sports-exchange-guide"],
["Casino Games Guide","Casino Games Guide","Slots, blackjack, roulette, baccarat, Teen Patti, Dragon Tiger and Andar Bahar explained in simple language.","blog-casino-games-guide.html","casino-games-guide"],
["Live Casino Guide","Live Casino Guide","How live dealer tables work, what to check on mobile and how to plan responsible sessions.","blog-live-casino-guide.html","live-casino-guide"],
["Aviator Guide","Aviator Guide","Crash game basics, volatility and why pre-set limits matter in fast rounds.","blog-aviator-guide.html","aviator-guide"],
["Teen Patti Guide","Teen Patti Guide","A compact introduction to Teen Patti table flow, etiquette and responsible play habits.","blog-teen-patti-guide.html","teen-patti-guide"]
];
const postSections=["What This Guide Covers","How the Format Works","Key Safety Checks","Mobile Experience","Responsible Gaming FAQ"];
const pageData={
home:{title:"GATHR",kicker:"Sword sharp. Crown ready.",intro:"A premium sports exchange and casino guide built around cricket, football, live tables, Aviator, VIP rewards and responsible gaming. Dark visuals, direct CTAs and content that keeps the user journey focused.",type:"home"},
cricket:{title:"Cricket Exchange",kicker:"Online cricket ID guide",intro:"Explore cricket exchange basics, Online Cricket ID education, IPL and T20 guides, market terminology and responsible habits for cricket fans.",type:"article",sections:["Online Cricket ID Basics","Cricket Exchange Market Flow","IPL and T20 Guide","Choosing a Cricket ID Provider","Responsible Cricket Play"],keywords:["Online Cricket ID","Cricket Exchange","Cricket Betting Guide","Cricket ID Provider","Best Cricket ID"]},
football:{title:"Football Exchange",kicker:"Live sports momentum",intro:"A focused football exchange guide covering pre-match research, live sports movement, mobile access and support expectations.",type:"article",sections:["Football Exchange Basics","Live Match Markets","Mobile Football Access","Research Before a Match","Responsible Football Gaming"],keywords:["Football Exchange","Sports Exchange Guide","Live Sports"]},
casino:{title:"Casino Games",kicker:"Tables, slots and card rooms",intro:"Slots, blackjack, roulette, baccarat, Teen Patti, Dragon Tiger and Andar Bahar presented in a premium guide layout with responsible gaming context.",type:"article",sections:["Slots and Volatility","Blackjack and Table Flow","Roulette and Baccarat","Teen Patti and Indian Card Games","Casino Session Planning"],keywords:["Casino Games Guide","Teen Patti Guide"]},
live:{title:"Live Casino",kicker:"Real-time table experience",intro:"Learn how live casino tables work, what to expect from dealers, streams, table limits, mobile compatibility and safer session planning.",type:"article",sections:["Live Dealer Basics","Roulette and Blackjack Tables","Baccarat Rooms","Mobile Live Casino","Etiquette and Limits"],keywords:["Live Casino Guide","Casino Games Guide"]},
aviator:{title:"Aviator",kicker:"Crash game clarity",intro:"Aviator-style games move quickly. This page explains the format, volatility, cash-out thinking and why limits matter before the round begins.",type:"article",sections:["How Aviator Works","Volatility and Timing","Common Mistakes","Mobile Play","Responsible Limits"],keywords:["Aviator Guide","Online Betting Guide"]},
promotions:{title:"Promotions",kicker:"Rewards with terms first",intro:"Welcome offers, seasonal rewards and reload-style campaigns should always be checked against clear terms, eligibility and responsible limits.",type:"article",sections:["Welcome Promotions","Sports Rewards","Casino Offers","VIP Boosts","Reading Terms"],keywords:["Online Betting Guide","VIP Rewards"]},
vip:{title:"VIP Club",kicker:"Bronze to diamond",intro:"A polished VIP Club page for Bronze, Silver, Gold, Platinum and Diamond tiers, designed around premium support, tailored rewards and responsible value.",type:"vip"},
blog:{title:"GATHR Blog",kicker:"SEO gaming guides",intro:"Long-form guides for Online Cricket ID, Cricket Exchange, IPL, T20, Sports Exchange, Casino Games, Live Casino, Aviator and Teen Patti.",type:"blog"},
about:{title:"About GATHR",kicker:"Premium information brand",intro:"GATHR combines a sword-and-crown identity with polished sports and gaming education for adults who want a clear, modern content experience.",type:"article",sections:["Our Positioning","What We Publish","Design Philosophy","Responsible Information","How We Link Topics"],keywords:["GATHR","Sports Exchange Guide"]},
contact:{title:"Contact Us",kicker:"Support and enquiries",intro:"Reach GATHR for general enquiries, content updates, support routing, collaboration and responsible gaming resources.",type:"contact"},
responsible:{title:"Responsible Gaming",kicker:"18+ only",intro:"Gaming should be treated as entertainment, never income. Set budgets, set time limits and pause when play stops feeling controlled.",type:"article",sections:["Age Restriction","Budget Limits","Time Controls","Warning Signs","Getting Help"],keywords:["Responsible Gaming","Online Betting Guide"]},
privacy:{title:"Privacy Policy",kicker:"Clear data practices",intro:"This privacy policy explains the types of information a website like GATHR may collect, how it may be used and the choices visitors should have.",type:"article",sections:["Information We Collect","Cookies and Analytics","Contact Data","Third-party Links","User Choices"],keywords:["Privacy Policy"]},
terms:{title:"Terms and Conditions",kicker:"Use the site responsibly",intro:"These terms explain informational use, age restrictions, third-party links, intellectual property and responsible gaming disclaimers.",type:"article",sections:["Informational Content","Age Restriction","Third-party Links","No Guarantees","Policy Updates"],keywords:["Terms and Conditions"]},
faq:{title:"Frequently Asked Questions",kicker:"Quick answers",intro:"Answers to common questions about GATHR, cricket exchange guides, casino content, VIP rewards, support and responsible gaming.",type:"faq"}
};
function card(title,text,icon="✦"){return `<article class="card"><div class="icon">${icon}</div><h3>${title}</h3><p>${text}</p></article>`}
function cta(){return `<div class="cta-row"><a class="btn primary" href="contact-us.html">Join Now</a><a class="btn secondary" href="https://wa.me/">WhatsApp Support</a></div>`}
function hero(p){return `<section class="hero"><div class="hero-inner"><div class="eyebrow">${p.kicker}</div><h1>${p.title}</h1><p>${p.intro}</p>${cta()}<div class="badge-row"><span class="badge">18+ Responsible Gaming</span><span class="badge">Sword & Crown Theme</span><span class="badge">Mobile First</span></div></div></section>`}
function home(p){return hero(p)+section("Features","Built for a polished sports and gaming journey.",`<div class="grid cards">${features.map((x,i)=>card(x,["Quick access flows with clear information.","Security-first messaging and privacy-aware pages.","Support CTAs placed where users expect them.","Responsive layouts tuned for every screen.","Luxury visuals with direct conversion paths.","Tiered reward content for loyal users."][i],["↯","⚔","●","▣","♛","◆"][i])).join("")}</div>`)+section("Sports Exchange","Cricket, football, tennis and live sports guides linked across the site.",`<div class="grid four">${sports.map(x=>card(x,`Read premium ${x.toLowerCase()} content with simple navigation and responsible context.`,"⚔")).join("")}</div>`,"alt")+section("Casino Section","Live casino, slots, blackjack, roulette, baccarat and Indian card game guides.",`<div class="grid four">${casino.map(x=>card(x,`Explore ${x} basics, table flow and safer session planning.`,"♛")).join("")}</div>`)+why()+vipBlock()+testimonials()+blogGrid()+faqBlock(commonFaq)}
function section(title,desc,body,cls=""){return `<section class="section ${cls}"><div class="section-inner"><div class="section-head"><div><div class="eyebrow">GATHR</div><h2>${title}</h2></div><p>${desc}</p></div>${body}</div></section>`}
function why(){return section("Why Choose GATHR","A conversion-focused experience with strong internal linking and responsible messaging.",`<div class="split"><div>${["Trusted Platform","Instant Access","Mobile Compatible","Secure Experience","Professional Support"].map(x=>card(x,`${x} content is presented with clear expectations and no unrealistic promises.`,"◆")).join("")}</div><div class="feature-panel"><div><div class="eyebrow">Crown Standard</div><h2>Premium black and red gaming interface</h2><p>Built for scanning, comparing and moving into the right guide quickly.</p></div></div></div>`,"alt")}
function vipBlock(){return section("VIP Program","Five tiers with premium positioning and responsible value.",`<div class="grid cards">${["Bronze","Silver","Gold","Platinum","Diamond"].map((t,i)=>`<article class="card vip-tier"><div class="icon">♛</div><h3>${t}</h3><p><strong>${["Starter access","Priority updates","Reward boosts","Premium support","Elite recognition"][i]}</strong></p><p>Tier information should always be read with current terms, eligibility and responsible play limits.</p></article>`).join("")}</div>`)}
function testimonials(){return section("Testimonials","Short, polished trust signals for a premium landing page.",`<div class="grid three cards">${["The layout makes cricket and casino topics easy to compare.","The VIP structure feels premium without hiding the important terms.","Responsible gaming links are visible, which builds trust."].map((t,i)=>card(["Arjun M.","Rhea S.","Kabir P."][i],t,"★")).join("")}</div>`,"alt")}
function blogGrid(){return section("Latest Blog Posts","SEO-focused guides with internal links across major topics.",`<div class="grid cards">${blogPosts.slice(0,6).map(b=>`<article class="article-card"><div class="thumb" loading="lazy"></div><div class="body"><div class="meta">${b[1]}</div><h3>${b[0]}</h3><p>${b[2]}</p><a class="btn secondary" href="${b[3]}">Read Guide</a></div></article>`).join("")}</div>`)}
function article(p){let toc=p.sections.map((s,i)=>`<a href="#s${i}">${s}</a>`).join("");let body=p.sections.map((s,i)=>`<h2 id="s${i}">${s}</h2><p>${articleText(s,p.title)}</p><ul><li>Check terms, local rules and age requirements before taking action.</li><li>Use mobile-friendly pages, secure accounts and clear session limits.</li><li>Compare support, privacy and responsible gaming tools before choosing any service.</li></ul>`).join("");return hero(p)+section("Guide Overview",p.intro,`<div class="article-layout"><article class="article-body"><div class="mini-img" role="img" aria-label="GATHR premium gaming visual"></div>${body}<h2>Related Guides</h2><p>Continue with <a href="blog.html">GATHR Blog</a>, <a href="responsible-gaming.html">Responsible Gaming</a>, <a href="vip-club.html">VIP Club</a> and <a href="contact-us.html">Contact Us</a>.</p></article><aside class="toc"><h3>Table of Contents</h3>${toc}<div class="cta-row"><a class="btn primary" href="contact-us.html">Join Now</a></div></aside></div>`)+faqBlock(commonFaq)}
function articleText(s,title){return `${s} is a core part of the ${title} experience. GATHR presents the topic in plain language so visitors can understand the format, compare important details and avoid rushed decisions. The best user journey is direct, transparent and supported by visible responsible-gaming information.`}
function blog(){return hero(pageData.blog)+section("Our Articles","Keyword-targeted guides with featured images, FAQs, related posts and internal links.",`<div class="article-layout"><div class="grid cards">${blogPosts.map(b=>`<article class="article-card"><div class="thumb"></div><div class="body"><div class="meta">${b[1]}</div><h3>${b[0]}</h3><p>${b[2]}</p><a class="btn secondary" href="${b[3]}">Open Article</a></div></article>`).join("")}</div><aside class="toc"><h3>Categories</h3>${["Cricket ID","Sports Exchange","Casino Games","Live Casino","Aviator","Responsible Gaming"].map(x=>`<a href="blog.html">${x}</a>`).join("")}</aside></div>`)+faqBlock(commonFaq)}
function post(){const slug=document.body.dataset.post;const b=blogPosts.find(x=>x[4]===slug)||blogPosts[0];const p={title:b[0],kicker:b[1],intro:b[2]};let toc=postSections.map((s,i)=>`<a href="#p${i}">${s}</a>`).join("");let body=postSections.map((s,i)=>`<h2 id="p${i}">${s}</h2><p>${b[1]} is an important search topic for adult users comparing sports exchange and casino information. This GATHR article focuses on plain-language education, mobile usability, transparent terms, support checks and responsible gaming habits instead of unrealistic promises.</p><p>Before using any third-party platform, confirm age eligibility, local regulations, account security, privacy practices and available limits. Treat every session as entertainment, keep a fixed budget and stop when the experience no longer feels controlled.</p>`).join("");return hero(p)+section("Featured Article",b[2],`<div class="article-layout"><article class="article-body"><div class="mini-img"></div>${body}<h2>Related Posts</h2><p>${blogPosts.filter(x=>x[4]!==slug).slice(0,3).map(x=>`<a href="${x[3]}">${x[0]}</a>`).join(" · ")}</p><p>Also visit <a href="cricket-exchange.html">Cricket Exchange</a>, <a href="casino-games.html">Casino Games</a>, <a href="responsible-gaming.html">Responsible Gaming</a> and <a href="contact-us.html">Contact Us</a>.</p></article><aside class="toc"><h3>Table of Contents</h3>${toc}<a href="blog.html">Back to Blog</a></aside></div>`)+faqBlock(commonFaq)}
function contact(p){return hero(p)+section("Contact Information","Use the right path for the right enquiry.",`<div class="grid cards"><div class="contact-box"><h3>WhatsApp Support</h3><p>Use the floating WhatsApp button for quick contact routing.</p><a class="btn primary" href="https://wa.me/">Open WhatsApp</a></div><div class="contact-box"><h3>Content Enquiries</h3><p>Request updates to guides, blog topics, internal links and compliance information.</p><a class="btn secondary" href="mailto:hello@gathr.example">Email GATHR</a></div><div class="contact-box"><h3>Responsible Gaming</h3><p>Find age, budget, time-limit and support information before engaging with any service.</p><a class="btn secondary" href="responsible-gaming.html">Read Policy</a></div></div>`)+faqBlock(commonFaq)}
function faqBlock(items){return section("Frequently Asked Questions","Clear answers on every major page.",`<div class="faq-list">${items.map(x=>`<div class="faq-item"><button class="faq-q" type="button">${x[0]}</button><div class="faq-a">${x[1]}</div></div>`).join("")}</div>`)}
function faqPage(p){return hero(p)+faqBlock([...commonFaq,["What pages are included?","Home, Cricket Exchange, Football Exchange, Casino Games, Live Casino, Aviator, Promotions, VIP Club, Blog, About, Contact, Responsible Gaming, Privacy Policy, Terms and FAQ."],["What keywords does the blog target?","Online Cricket ID, Cricket Exchange, Cricket Betting Guide, Cricket ID Provider, Best Cricket ID, IPL Guide, T20 Betting Guide, Sports Exchange Guide, Casino Games Guide, Live Casino Guide, Aviator Guide and Teen Patti Guide."]])}
function vip(){return hero(pageData.vip)+vipBlock()+section("VIP Benefits","Premium positioning with clear expectations.",`<div class="grid cards">${["Priority support","Exclusive updates","Reward calendar","Personalized journeys","Diamond recognition","Terms-first transparency"].map(x=>card(x,`${x} is described as a program feature and should always be checked against current eligibility rules.`,"♛")).join("")}</div>`)+faqBlock(commonFaq)}
function render(){const key=document.body.dataset.page||"home";const p=pageData[key]||pageData.home;document.querySelector("#siteNav").innerHTML=navLinks.map(n=>`<a class="${n[2]===key?"active":""}" href="${n[1]}">${n[0]}</a>`).join("");const app=document.querySelector("#app");app.innerHTML=key==="post"?post():p.type==="home"?home(p):p.type==="blog"?blog():p.type==="contact"?contact(p):p.type==="faq"?faqPage(p):p.type==="vip"?vip():article(p);footer();schema(key==="post"?{title:document.title}:p,key);bindUi()}
function footer(){document.querySelector("#footer").innerHTML=`<div class="footer-inner"><div class="footer-top"><div><img class="footer-logo" src="gathr.jpeg" alt="GATHR logo"><p>Premium sports exchange and casino guide with visible responsible gaming information. 18+ only.</p></div><div class="footer-links"><div><h3>Sports</h3><a href="cricket-exchange.html">Cricket Exchange</a><a href="football-exchange.html">Football Exchange</a><a href="blog.html">IPL Guide</a></div><div><h3>Casino</h3><a href="casino-games.html">Casino Games</a><a href="live-casino.html">Live Casino</a><a href="aviator.html">Aviator</a></div><div><h3>Company</h3><a href="about-us.html">About Us</a><a href="contact-us.html">Contact Us</a><a href="vip-club.html">VIP Club</a></div><div><h3>Legal</h3><a href="responsible-gaming.html">Responsible Gaming</a><a href="privacy-policy.html">Privacy Policy</a><a href="terms-conditions.html">Terms & Conditions</a></div></div></div><div class="trust-row"><span>Responsible Gaming</span><span>Secure Information</span><span class="age">18+</span></div><p>Powered by GATHR. Follow us: Instagram · X · Telegram · YouTube</p></div>`}
function schema(p,key){const faq=commonFaq.map(x=>({"@type":"Question",name:x[0],acceptedAnswer:{"@type":"Answer",text:x[1]}}));const data=[{"@context":"https://schema.org","@type":"Organization",name:"GATHR",url:"https://gathr.example/",logo:"https://gathr.example/gathr.jpeg"},{"@context":"https://schema.org","@type":"WebSite",name:"GATHR",url:"https://gathr.example/"},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://gathr.example/"},{"@type":"ListItem",position:2,name:p.title,item:`https://gathr.example/${location.pathname.split("/").pop()||"index.html"}`}]},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq}];data.forEach(d=>{const s=document.createElement("script");s.type="application/ld+json";s.textContent=JSON.stringify(d);document.head.appendChild(s)})}
function bindUi(){document.querySelectorAll("a.btn").forEach(btn=>btn.href=whatsappUrl);document.querySelectorAll(".float-whatsapp").forEach(btn=>btn.href=whatsappUrl);document.querySelectorAll(".faq-q").forEach(btn=>btn.addEventListener("click",()=>btn.parentElement.classList.toggle("open")));const nav=document.querySelector(".nav"),menu=document.querySelector(".menu-toggle");menu.addEventListener("click",()=>{nav.classList.toggle("open");menu.setAttribute("aria-expanded",nav.classList.contains("open"))});const top=document.querySelector(".back-top");window.addEventListener("scroll",()=>top.classList.toggle("show",scrollY>500));top.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}))}
window.addEventListener("load",()=>document.body.classList.add("loaded"));
document.addEventListener("DOMContentLoaded",render);
